application: thefacebooktimeline
version: 1
runtime: python
api_version: 1

handlers:
- url: /examples/jfk/(.*)
  static_files: examples/jfk/\1
  upload: examples/jfk/(.*)

- url: /
  script: main.py

